FROM python:3.8-alpine
LABEL author="V"

RUN apk update \
    && apk upgrade \
    && apk add git \
    && pip install pipenv

WORKDIR /tests

COPY tests/requirements.txt ./
RUN pipenv install -r requirements.txt

COPY tests/ ./

ENTRYPOINT pipenv run pytest test_app.py --url http://app:5000
